export const GETALL_MILKTYPES = "GETALL_MILKTYPES";
export const DELETE_MILKTYPES = "DELETE_MILKTYPES";
export const POST_MILKTYPES = "POST_MILKTYPES";
export const UPDATE_MILKTYPES = "UPDATE_MILKTYPES";
export const GET_SINGLE_MILKTYPES = "GET_SINGLE_MILKTYPES";
