export const GETALL_USERS_SUCCESS = "GETALL_USERS_SUCCESS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const POST_USERS_SUCCESS = "POST_USERS_SUCCESS";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GETALL_CUSOMERS_SUCCESS = "GETALL_CUSOMERS_SUCCESS";
export const DELETE_CUSOMERS_SUCCESS = "DELETE_CUSOMERS_SUCCESS";
export const POST_CUSOMERS_SUCCESS = "POST_CUSOMERS_SUCCESS";
export const UPDATE_CUSOMERS_SUCCESS = "UPDATE_CUSOMERS_SUCCESS";

export const GETALL_CUSOMERS_MILKDATA_SUCCESS =
  "GETALL_CUSOMERS_MILKDATA_SUCCESS";
export const DELETE_CUSOMERS_MILKDATA_SUCCESS =
  "DELETE_CUSOMERS_MILKDATA_SUCCESS";
export const POST_CUSOMERS_MILKDATA_SUCCESS = "POST_CUSOMERS_MILKDATA_SUCCESS";
export const UPDATE_CUSOMERS_MILKDATA_SUCCESS =
  "UPDATE_CUSOMERS_MILKDATA_SUCCESS";
export const GET_SINGLE_CUSOMERS_MILKDATA_SUCCESS =
  "GET_SINGLE_CUSOMERS_MILKDATA_SUCCESS";
export const FORGOT_PASSWORD =
  "FORGOT_PASSWORD";
export const RESET_PASSWORD =
  "RESET_PASSWORD";